import type { LucideIcon } from "lucide-react";
import type { IconType } from "react-icons";

export type AppIcon = LucideIcon | IconType;
import {
  // Combat / Weapon
  Anvil,
  Axe,
  Bomb,
  Construction,
  Cross,
  Crosshair,
  Crown,
  Gavel,
  Hammer,
  Pickaxe,
  PocketKnife,
  Skull,
  Slice,
  Sword,
  Swords,
  Target,
  Trophy,
  Wand,
  WandSparkles,
  // Defense / Protection
  BrickWall,
  Castle,
  Fence,
  HardHat,
  Lock,
  LockKeyhole,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShieldPlus,
  // Elemental / Nature
  Clover,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Cloudy,
  Earth,
  Flower,
  Flower2,
  Leaf,
  LeafyGreen,
  Mountain,
  Rainbow,
  Shrub,
  Sprout,
  Sunrise,
  Sunset,
  Tornado,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Wind,
  // Fire / Heat
  CookingPot,
  FireExtinguisher,
  Flame,
  FlameKindling,
  Fuel,
  Heater,
  ThermometerSun,
  // Ice / Cold
  IceCreamCone,
  MountainSnow,
  Snowflake,
  SunSnow,
  ThermometerSnowflake,
  // Water / Ocean
  Dam,
  Droplet,
  Droplets,
  Fish,
  Sailboat,
  Shell,
  ShowerHead,
  Waves,
  // Lightning / Energy
  PlugZap,
  Zap,
  // Light / Holy
  Church,
  Flashlight,
  FlashlightOff,
  Haze,
  Lightbulb,
  Medal,
  Sparkle,
  Sparkles,
  Star,
  StarHalf,
  StarOff,
  Stars,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  // Dark / Arcane
  CircleDot,
  CircleDotDashed,
  Drama,
  Eclipse,
  EyeClosed,
  Ghost,
  Moon,
  MoonStar,
  Omega,
  Orbit,
  Origami,
  Radiation,
  VenetianMask,
  // Poison / Toxin
  Biohazard,
  Cannabis,
  FlaskConical,
  FlaskRound,
  Pipette,
  SprayCan,
  Syringe,
  TestTube,
  TestTubes,
  // Psychic / Mind
  Brain,
  BrainCircuit,
  BrainCog,
  Ear,
  Eye,
  EyeOff,
  Fingerprint,
  Radar,
  ScanEye,
  ScanFace,
  Speech,
  Telescope,
  // Life / Healing
  Bandage,
  HandCoins,
  HandHeart,
  HandHelping,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Pill,
  PillBottle,
  ScanHeart,
  Stethoscope,
  // Crystal / Mineral
  Cone,
  Cuboid,
  Diamond,
  DiamondMinus,
  DiamondPlus,
  Gem,
  Hexagon,
  Pentagon,
  Pyramid,
  // Sound / Sonic
  AudioLines,
  AudioWaveform,
  Bell,
  BellElectric,
  BellRing,
  Drum,
  Guitar,
  Megaphone,
  Music,
  Music2,
  Piano,
  Volume2,
  // Time / Gravity
  Clock,
  History,
  Hourglass,
  Infinity,
  Magnet,
  RotateCcw,
  RotateCw,
  Timer,
  TimerReset,
  Weight,
  // Beast / Animal
  Bird,
  Bone,
  Bug,
  Cat,
  Dog,
  Drumstick,
  Egg,
  Feather,
  PawPrint,
  Rabbit,
  Rat,
  Snail,
  Squirrel,
  Turtle,
  Worm,
  // Tech / Construct
  Bolt,
  Bot,
  BotMessageSquare,
  CircuitBoard,
  Cog,
  Cpu,
  Gamepad2,
  HardDrive,
  Joystick,
  Microchip,
  Plug,
  Rocket,
  Satellite,
  Wrench,
  // Magic / Spell
  Atom,
  BookOpen,
  Dna,
  Scroll,
  ScrollText,
  Shapes,
  Variable,
  Waypoints,
  // People / Roles
  BicepsFlexed,
  CircleUser,
  Contact,
  HandMetal,
  PersonStanding,
  User,
  UserRound,
  Users,
  // Movement / Navigation
  Compass,
  Footprints,
  Globe,
  Landmark,
  Map,
  MapPin,
  Navigation2,
  Route,
  Signpost,
  // Buffs / Debuffs
  Activity,
  ArrowBigDown,
  ArrowBigUp,
  ArrowDown,
  ArrowUp,
  CircleArrowDown,
  CircleArrowUp,
  Gauge,
  Layers,
  Repeat,
  ShieldOff,
  TrendingDown,
  TrendingUp,
  VolumeOff,
  // Status Indicators
  AlertTriangle,
  Badge,
  BadgeAlert,
  BadgeCheck,
  CircleAlert,
  CircleCheck,
  CircleX,
  // Items / Equipment
  Archive,
  Backpack,
  Box,
  Coins,
  Dumbbell,
  Gift,
  Glasses,
  Package,
  Shirt,
  // Exploration / Utility
  Aperture,
  Blend,
  Bookmark,
  Flag,
  Focus,
  Hand,
  Milestone,
  Proportions,
  ScanSearch,
  Shovel,
  Siren,
  Spade,
  Tag,
  Tags,
  Tent,
  Wheat,
  Workflow,
  // New lucide additions
  // Defense
  ShieldBan,
  ShieldClose,
  ShieldEllipsis,
  ShieldMinus,
  ShieldQuestion,
  ShieldX,
  // Items
  Boxes,
  Container,
  Package2,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PackageX,
  ShoppingBag,
  Vault,
  // Books / Knowledge
  Book,
  BookA,
  BookCheck,
  BookCopy,
  BookDashed,
  BookHeart,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  // Keys / Doors
  DoorClosed,
  DoorOpen,
  Key,
  KeyRound,
  KeySquare,
  LockKeyholeOpen,
  LockOpen,
  Unlock,
  UnlockKeyhole,
  // Light Sources
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  // Food / Consumables
  CupSoda,
  UtensilsCrossed,
  Utensils,
  Wine,
  // Misc
  Armchair,
  ChefHat,
  Club,
  FlaskConicalOff,
  GraduationCap,
  Handshake,
  HandPlatter,
  Headphones,
  Headset,
  LightbulbOff,
  Ribbon,
  Scale,
  Scale3d,
  SignpostBig,
  Wand2,
} from "lucide-react";
import {
  // GI: Weapons — Blades
  GiBroadsword,
  GiCrossedSwords,
  GiPlainDagger,
  GiSacrificialDagger,
  GiStiletto,
  GiKatana,
  GiSaberSlash,
  GiSwordBrandish,
  GiSwordInStone,
  GiTwoHandedSword,
  GiPointySword,
  GiSwordSpade,
  GiShiningSword,
  GiCloakDagger,
  // GI: Weapons — Axes & Blunt
  GiBattleAxe,
  GiWarAxe,
  GiThorHammer,
  GiSpikedMace,
  GiFlangedMace,
  GiMaceHead,
  GiFlail,
  GiCrookFlail,
  GiWoodClub,
  // GI: Weapons — Ranged
  GiBowArrow,
  GiPocketBow,
  GiCrossbow,
  GiArrowCluster,
  GiMusket,
  GiPistolGun,
  GiSlingshot,
  GiThrownDaggers,
  GiThrownSpear,
  GiBoomerang,
  GiThreePointedShuriken,
  GiSaberAndPistol,
  // GI: Weapons — Polearms
  GiTrident,
  GiHalberd,
  GiGlaive,
  // GI: Weapons — Staves & Magic
  GiWizardStaff,
  GiCrystalWand,
  GiOrbWand,
  GiMagicLamp,
  // GI: Armor — Head
  GiVisoredHelm,
  GiClosedBarbute,
  GiPointyHat,
  GiCowled,
  GiBandana,
  GiCrown as GiCrownIcon,
  GiTiara,
  GiHoodedFigure,
  GiHelmet,
  GiHeavyHelm,
  GiLightHelm,
  GiHornedHelm,
  GiSpartanHelmet,
  GiVikingHelmet,
  GiSamuraiHelmet,
  GiElfHelmet,
  GiDwarfHelmet,
  GiCrestedHelmet,
  GiBlackKnightHelm,
  GiHeadbandKnot,
  // GI: Armor — Body
  GiChestArmor,
  GiLeatherArmor,
  GiBreastplate,
  GiChainMail,
  GiMailShirt,
  GiScaleMail,
  GiArmorVest,
  GiNinjaArmor,
  GiLayeredArmor,
  GiAbdominalArmor,
  GiTrenchBodyArmor,
  GiCapeArmor,
  GiSpikedArmor,
  GiRobe,
  // GI: Armor — Hands
  GiGauntlet,
  GiGloves,
  GiBracers,
  GiMailedFist,
  GiArmorPunch,
  // GI: Armor — Feet
  GiBoots,
  GiLegArmor,
  GiGreaves,
  GiWalkingBoot,
  GiLeatherBoot,
  GiMetalBoot,
  GiSteeltoeBoots,
  GiBootStomp,
  // GI: Armor — Shoulders & Other
  GiShoulderArmor,
  GiSpikedShoulderArmor,
  GiShoulderScales,
  GiBeltArmor,
  GiArmoredPants,
  // GI: Shields
  GiShield as GiShieldIcon,
  GiRoundShield,
  GiBoltShield,
  GiShieldReflect,
  GiSpikedShield,
  GiTemplarShield,
  // GI: Accessories — Jewelry
  GiRing,
  GiNecklace,
  GiGemPendant,
  GiEarrings,
  GiCrystalBall,
  GiCharm,
  GiGemChain,
  // GI: Accessories — Cloaks & Belts
  GiCape as GiCapeIcon,
  GiCloak as GiCloakIcon,
  GiVampireCape,
  GiWingCloak,
  GiBelt,
  GiBeltBuckles,
  // GI: Professions / Classes
  GiMountedKnight,
  GiKnightBanner,
  GiNinjaHead,
  GiWitchFlight,
  GiWitchFace,
  GiMonkFace,
  GiMeditation,
  GiArcheryTarget,
  GiSwordman,
  GiBarbarian,
  GiFencer,
  GiBowman,
  GiTank,
  GiTemplarEye,
  // GI: Status Effects
  GiPoison,
  GiNightSleep,
  GiSleepy,
  GiFrozenBlock,
  GiBurningDot,
  GiStarStruck,
  GiBlindfold,
  GiSightDisabled,
  GiSilenced,
  GiMagicShield,
  GiHealthPotion,
  GiMagicPotion,
  GiSprint,
  GiSlowBlob,
  // GI: Magic Schools
  GiFireball,
  GiIceBolt,
  GiPowerLightning,
  GiLightningTrio,
  GiChainLightning,
  GiHolyGrail,
  GiDeathSkull,
  GiPoisonBottle,
  GiMagicSwirl,
  GiSpiralArrow,
  // GI: Items / Loot
  GiChest,
  GiLockedChest,
  GiOpenChest,
  GiGoldBar,
  GiGoldNuggets,
  GiCoinsPile,
  GiScrollUnfurled,
  GiSpellBook,
  GiPotionBall,
} from "react-icons/gi";
import { useState, useMemo } from "react";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "~/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { Search, ChevronsUpDown } from "lucide-react";
import { cn } from "~/lib/utils";

export interface IconGroup {
  label: string;
  collection: "lucide" | "game-icons";
  icons: Record<string, AppIcon>;
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: "Combat / Weapon",
    collection: "lucide",
    icons: {
      Anvil,
      Axe,
      Bomb,
      Construction,
      Cross,
      Crosshair,
      Crown,
      Gavel,
      Hammer,
      Pickaxe,
      PocketKnife,
      Skull,
      Slice,
      Sword,
      Swords,
      Target,
      Trophy,
      Wand,
      WandSparkles,
    },
  },
  {
    label: "Defense / Protection",
    collection: "lucide",
    icons: {
      BrickWall,
      Castle,
      Fence,
      HardHat,
      Lock,
      LockKeyhole,
      Shield,
      ShieldAlert,
      ShieldBan,
      ShieldCheck,
      ShieldClose,
      ShieldEllipsis,
      ShieldHalf,
      ShieldMinus,
      ShieldPlus,
      ShieldQuestion,
      ShieldX,
    },
  },
  {
    label: "Elemental / Nature",
    collection: "lucide",
    icons: {
      Clover,
      Cloud,
      CloudDrizzle,
      CloudFog,
      CloudHail,
      CloudLightning,
      CloudMoon,
      CloudMoonRain,
      CloudRain,
      CloudRainWind,
      CloudSnow,
      CloudSun,
      Cloudy,
      Earth,
      Flower,
      Flower2,
      Leaf,
      LeafyGreen,
      Mountain,
      Rainbow,
      Shrub,
      Sprout,
      Sunrise,
      Sunset,
      Tornado,
      TreeDeciduous,
      TreePalm,
      TreePine,
      Trees,
      Wind,
    },
  },
  {
    label: "Fire / Heat",
    collection: "lucide",
    icons: {
      CookingPot,
      FireExtinguisher,
      Flame,
      FlameKindling,
      Fuel,
      Heater,
      ThermometerSun,
    },
  },
  {
    label: "Ice / Cold",
    collection: "lucide",
    icons: {
      IceCreamCone,
      MountainSnow,
      Snowflake,
      SunSnow,
      ThermometerSnowflake,
    },
  },
  {
    label: "Water / Ocean",
    collection: "lucide",
    icons: {
      Dam,
      Droplet,
      Droplets,
      Fish,
      Sailboat,
      Shell,
      ShowerHead,
      Waves,
    },
  },
  {
    label: "Lightning / Energy",
    collection: "lucide",
    icons: {
      PlugZap,
      Zap,
    },
  },
  {
    label: "Light / Holy",
    collection: "lucide",
    icons: {
      Church,
      Flashlight,
      FlashlightOff,
      Haze,
      Lightbulb,
      Medal,
      Sparkle,
      Sparkles,
      Star,
      StarHalf,
      StarOff,
      Stars,
      Sun,
      SunDim,
      SunMedium,
      SunMoon,
    },
  },
  {
    label: "Dark / Arcane",
    collection: "lucide",
    icons: {
      CircleDot,
      CircleDotDashed,
      Drama,
      Eclipse,
      EyeClosed,
      Ghost,
      Moon,
      MoonStar,
      Omega,
      Orbit,
      Origami,
      Radiation,
      VenetianMask,
    },
  },
  {
    label: "Poison / Toxin",
    collection: "lucide",
    icons: {
      Biohazard,
      Cannabis,
      FlaskConical,
      FlaskRound,
      Pipette,
      SprayCan,
      Syringe,
      TestTube,
      TestTubes,
    },
  },
  {
    label: "Psychic / Mind",
    collection: "lucide",
    icons: {
      Brain,
      BrainCircuit,
      BrainCog,
      Ear,
      Eye,
      EyeOff,
      Fingerprint,
      Radar,
      ScanEye,
      ScanFace,
      Speech,
      Telescope,
    },
  },
  {
    label: "Life / Healing",
    collection: "lucide",
    icons: {
      Bandage,
      HandCoins,
      HandHeart,
      HandHelping,
      Heart,
      HeartCrack,
      HeartHandshake,
      HeartOff,
      HeartPulse,
      Pill,
      PillBottle,
      ScanHeart,
      Stethoscope,
    },
  },
  {
    label: "Crystal / Mineral",
    collection: "lucide",
    icons: {
      Cone,
      Cuboid,
      Diamond,
      DiamondMinus,
      DiamondPlus,
      Gem,
      Hexagon,
      Pentagon,
      Pyramid,
    },
  },
  {
    label: "Sound / Sonic",
    collection: "lucide",
    icons: {
      AudioLines,
      AudioWaveform,
      Bell,
      BellElectric,
      BellRing,
      Drum,
      Guitar,
      Megaphone,
      Music,
      Music2,
      Piano,
      Volume2,
    },
  },
  {
    label: "Time / Gravity",
    collection: "lucide",
    icons: {
      Clock,
      History,
      Hourglass,
      Infinity,
      Magnet,
      RotateCcw,
      RotateCw,
      Timer,
      TimerReset,
      Weight,
    },
  },
  {
    label: "Beast / Animal",
    collection: "lucide",
    icons: {
      Bird,
      Bone,
      Bug,
      Cat,
      Dog,
      Drumstick,
      Egg,
      Feather,
      PawPrint,
      Rabbit,
      Rat,
      Snail,
      Squirrel,
      Turtle,
      Worm,
    },
  },
  {
    label: "Tech / Construct",
    collection: "lucide",
    icons: {
      Bolt,
      Bot,
      BotMessageSquare,
      CircuitBoard,
      Cog,
      Cpu,
      Gamepad2,
      HardDrive,
      Joystick,
      Microchip,
      Plug,
      Rocket,
      Satellite,
      Wrench,
    },
  },
  {
    label: "Magic / Spell",
    collection: "lucide",
    icons: {
      Atom,
      BookOpen,
      Dna,
      Scroll,
      ScrollText,
      Shapes,
      Variable,
      Waypoints,
    },
  },
  {
    label: "People / Roles",
    collection: "lucide",
    icons: {
      BicepsFlexed,
      CircleUser,
      Contact,
      HandMetal,
      PersonStanding,
      User,
      UserRound,
      Users,
    },
  },
  {
    label: "Movement / Navigation",
    collection: "lucide",
    icons: {
      Compass,
      Footprints,
      Globe,
      Landmark,
      Map,
      MapPin,
      Navigation2,
      Route,
      Signpost,
    },
  },
  {
    label: "Buffs / Debuffs",
    collection: "lucide",
    icons: {
      Activity,
      ArrowBigDown,
      ArrowBigUp,
      ArrowDown,
      ArrowUp,
      CircleArrowDown,
      CircleArrowUp,
      Gauge,
      Layers,
      Repeat,
      ShieldOff,
      TrendingDown,
      TrendingUp,
      VolumeOff,
    },
  },
  {
    label: "Status Indicators",
    collection: "lucide",
    icons: {
      AlertTriangle,
      Badge,
      BadgeAlert,
      BadgeCheck,
      CircleAlert,
      CircleCheck,
      CircleX,
    },
  },
  {
    label: "Items / Equipment",
    collection: "lucide",
    icons: {
      Archive,
      Backpack,
      Box,
      Boxes,
      Coins,
      Container,
      Dumbbell,
      Gift,
      Glasses,
      Package,
      Package2,
      PackageCheck,
      PackageOpen,
      PackagePlus,
      PackageX,
      Shirt,
      ShoppingBag,
      Vault,
    },
  },
  {
    label: "Exploration / Utility",
    collection: "lucide",
    icons: {
      Aperture,
      Armchair,
      Blend,
      Bookmark,
      ChefHat,
      Club,
      Flag,
      FlaskConicalOff,
      Focus,
      GraduationCap,
      Hand,
      Handshake,
      HandPlatter,
      Headphones,
      Headset,
      LightbulbOff,
      Milestone,
      Proportions,
      Ribbon,
      Scale,
      Scale3d,
      ScanSearch,
      Shovel,
      SignpostBig,
      Siren,
      Spade,
      Tag,
      Tags,
      Tent,
      Wand2,
      Wheat,
      Workflow,
    },
  },
  {
    label: "Books / Knowledge",
    collection: "lucide",
    icons: {
      Book,
      BookA,
      BookCheck,
      BookCopy,
      BookDashed,
      BookHeart,
      BookKey,
      BookLock,
      BookMarked,
      BookMinus,
      BookOpenCheck,
      BookOpenText,
      BookPlus,
      BookText,
      BookType,
      BookUp,
      BookUp2,
      BookUser,
      BookX,
    },
  },
  {
    label: "Keys / Doors",
    collection: "lucide",
    icons: {
      DoorClosed,
      DoorOpen,
      Key,
      KeyRound,
      KeySquare,
      LockKeyholeOpen,
      LockOpen,
      Unlock,
      UnlockKeyhole,
    },
  },
  {
    label: "Light Sources",
    collection: "lucide",
    icons: {
      Lamp,
      LampCeiling,
      LampDesk,
      LampFloor,
      LampWallDown,
      LampWallUp,
    },
  },
  {
    label: "Food / Consumables",
    collection: "lucide",
    icons: {
      CupSoda,
      Utensils,
      UtensilsCrossed,
      Wine,
    },
  },
  // ── Game Icons (react-icons/gi) ──────────────────────────
  {
    label: "GI: Weapons — Blades",
    collection: "game-icons",
    icons: {
      GiBroadsword,
      GiCloakDagger,
      GiCrossedSwords,
      GiKatana,
      GiPlainDagger,
      GiPointySword,
      GiSaberSlash,
      GiSacrificialDagger,
      GiShiningSword,
      GiStiletto,
      GiSwordBrandish,
      GiSwordInStone,
      GiSwordSpade,
      GiTwoHandedSword,
    },
  },
  {
    label: "GI: Weapons — Axes & Blunt",
    collection: "game-icons",
    icons: {
      GiBattleAxe,
      GiCrookFlail,
      GiFlail,
      GiFlangedMace,
      GiMaceHead,
      GiSpikedMace,
      GiThorHammer,
      GiWarAxe,
      GiWoodClub,
    },
  },
  {
    label: "GI: Weapons — Ranged",
    collection: "game-icons",
    icons: {
      GiArrowCluster,
      GiBoomerang,
      GiBowArrow,
      GiCrossbow,
      GiMusket,
      GiPistolGun,
      GiPocketBow,
      GiSaberAndPistol,
      GiSlingshot,
      GiThreePointedShuriken,
      GiThrownDaggers,
      GiThrownSpear,
    },
  },
  {
    label: "GI: Weapons — Polearms",
    collection: "game-icons",
    icons: {
      GiGlaive,
      GiHalberd,
      GiTrident,
    },
  },
  {
    label: "GI: Weapons — Staves & Magic",
    collection: "game-icons",
    icons: {
      GiCrystalWand,
      GiMagicLamp,
      GiOrbWand,
      GiWizardStaff,
    },
  },
  {
    label: "GI: Armor — Head",
    collection: "game-icons",
    icons: {
      GiBandana,
      GiBlackKnightHelm,
      GiClosedBarbute,
      GiCowled,
      GiCrestedHelmet,
      GiCrownIcon,
      GiDwarfHelmet,
      GiElfHelmet,
      GiHeadbandKnot,
      GiHeavyHelm,
      GiHelmet,
      GiHoodedFigure,
      GiHornedHelm,
      GiLightHelm,
      GiPointyHat,
      GiSamuraiHelmet,
      GiSpartanHelmet,
      GiTiara,
      GiVikingHelmet,
      GiVisoredHelm,
    },
  },
  {
    label: "GI: Armor — Body",
    collection: "game-icons",
    icons: {
      GiAbdominalArmor,
      GiArmorVest,
      GiBreastplate,
      GiCapeArmor,
      GiChainMail,
      GiChestArmor,
      GiLayeredArmor,
      GiLeatherArmor,
      GiMailShirt,
      GiNinjaArmor,
      GiRobe,
      GiScaleMail,
      GiSpikedArmor,
      GiTrenchBodyArmor,
    },
  },
  {
    label: "GI: Armor — Hands",
    collection: "game-icons",
    icons: {
      GiArmorPunch,
      GiBracers,
      GiGauntlet,
      GiGloves,
      GiMailedFist,
    },
  },
  {
    label: "GI: Armor — Feet",
    collection: "game-icons",
    icons: {
      GiBootStomp,
      GiBoots,
      GiGreaves,
      GiLeatherBoot,
      GiLegArmor,
      GiMetalBoot,
      GiSteeltoeBoots,
      GiWalkingBoot,
    },
  },
  {
    label: "GI: Armor — Shoulders & Other",
    collection: "game-icons",
    icons: {
      GiArmoredPants,
      GiBeltArmor,
      GiShoulderArmor,
      GiShoulderScales,
      GiSpikedShoulderArmor,
    },
  },
  {
    label: "GI: Shields",
    collection: "game-icons",
    icons: {
      GiBoltShield,
      GiRoundShield,
      GiShieldIcon,
      GiShieldReflect,
      GiSpikedShield,
      GiTemplarShield,
    },
  },
  {
    label: "GI: Accessories — Jewelry",
    collection: "game-icons",
    icons: {
      GiCharm,
      GiCrystalBall,
      GiEarrings,
      GiGemChain,
      GiGemPendant,
      GiNecklace,
      GiRing,
    },
  },
  {
    label: "GI: Accessories — Cloaks & Belts",
    collection: "game-icons",
    icons: {
      GiBelt,
      GiBeltBuckles,
      GiCapeIcon,
      GiCloakIcon,
      GiVampireCape,
      GiWingCloak,
    },
  },
  {
    label: "GI: Professions / Classes",
    collection: "game-icons",
    icons: {
      GiArcheryTarget,
      GiBarbarian,
      GiBowman,
      GiFencer,
      GiKnightBanner,
      GiMeditation,
      GiMonkFace,
      GiMountedKnight,
      GiNinjaHead,
      GiSwordman,
      GiTank,
      GiTemplarEye,
      GiWitchFace,
      GiWitchFlight,
    },
  },
  {
    label: "GI: Status Effects",
    collection: "game-icons",
    icons: {
      GiBlindfold,
      GiBurningDot,
      GiFrozenBlock,
      GiHealthPotion,
      GiMagicPotion,
      GiMagicShield,
      GiNightSleep,
      GiPoison,
      GiSightDisabled,
      GiSilenced,
      GiSleepy,
      GiSlowBlob,
      GiSprint,
      GiStarStruck,
    },
  },
  {
    label: "GI: Magic Schools",
    collection: "game-icons",
    icons: {
      GiChainLightning,
      GiDeathSkull,
      GiFireball,
      GiHolyGrail,
      GiIceBolt,
      GiLightningTrio,
      GiMagicSwirl,
      GiPoisonBottle,
      GiPowerLightning,
      GiSpiralArrow,
    },
  },
  {
    label: "GI: Items / Loot",
    collection: "game-icons",
    icons: {
      GiChest,
      GiCoinsPile,
      GiGoldBar,
      GiGoldNuggets,
      GiLockedChest,
      GiOpenChest,
      GiPotionBall,
      GiScrollUnfurled,
      GiSpellBook,
    },
  },
];

export const ICON_MAP: Record<string, AppIcon> = ICON_GROUPS.reduce<
  Record<string, AppIcon>
>((acc, group) => ({ ...acc, ...group.icons }), {});

export const DEFAULT_ICON_KEY = "CircleDot";

interface IconPickerProps {
  value?: string;
  onValueChange: (value: string) => void;
}

type CollectionFilter = "all" | "lucide" | "game-icons";

export function IconPicker({ value = DEFAULT_ICON_KEY, onValueChange }: IconPickerProps) {
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<CollectionFilter>("all");

  const SelectedIcon = ICON_MAP[value];

  const filteredGroups = useMemo(() => {
    const lowerSearch = search.toLowerCase();
    return ICON_GROUPS
      .filter((group) => tab === "all" || group.collection === tab)
      .map((group) => {
        const filtered = Object.entries(group.icons).filter(([key]) =>
          key.toLowerCase().includes(lowerSearch)
        );
        if (filtered.length === 0) return null;
        return { ...group, icons: Object.fromEntries(filtered) };
      })
      .filter(Boolean) as IconGroup[];
  }, [search, tab]);

  function handleSelect(key: string) {
    onValueChange(key);
    setOpen(false);
    setSearch("");
  }

  return (
    <Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) setSearch(""); }}>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          className="w-full justify-between font-normal"
        >
          <div className="flex items-center gap-2">
            {SelectedIcon && <SelectedIcon className="h-4 w-4" />}
            <span>{value}</span>
          </div>
          <ChevronsUpDown className="h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[440px] p-0 gap-0">
        <DialogHeader className="px-4 pt-4 pb-0">
          <DialogTitle className="text-base">Choose an Icon</DialogTitle>
        </DialogHeader>
        <div className="flex items-center gap-2 border-b px-4 py-2">
          <Search className="h-4 w-4 shrink-0 text-muted-foreground" />
          <Input
            placeholder="Search icons..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="h-8 border-0 p-0 shadow-none focus-visible:ring-0"
          />
        </div>
        <Tabs value={tab} onValueChange={(v) => setTab(v as CollectionFilter)}>
          <div className="border-b px-4 pt-1">
            <TabsList className="h-8 w-full">
              <TabsTrigger value="all" className="text-xs flex-1">All</TabsTrigger>
              <TabsTrigger value="lucide" className="text-xs flex-1">Lucide</TabsTrigger>
              <TabsTrigger value="game-icons" className="text-xs flex-1">Game Icons</TabsTrigger>
            </TabsList>
          </div>
          {(["all", "lucide", "game-icons"] as const).map((tabValue) => (
            <TabsContent key={tabValue} value={tabValue} className="mt-0">
              <div className="h-[350px] overflow-y-auto">
                {filteredGroups.length === 0 ? (
                  <div className="py-6 text-center text-sm text-muted-foreground">
                    No icons found.
                  </div>
                ) : (
                  <div className="p-3">
                    {filteredGroups.map((group) => (
                      <div key={group.label} className="mb-3">
                        <div className="px-1 pb-1 text-xs font-semibold text-muted-foreground">
                          {group.label}
                        </div>
                        <div className="grid grid-cols-10 gap-1">
                          {Object.entries(group.icons).map(([key, Icon]) => (
                            <button
                              key={key}
                              type="button"
                              title={key}
                              onClick={() => handleSelect(key)}
                              className={cn(
                                "flex h-8 w-8 items-center justify-center rounded-md hover:bg-accent hover:text-accent-foreground transition-colors",
                                value === key && "bg-accent text-accent-foreground ring-1 ring-primary"
                              )}
                            >
                              <Icon className="h-4 w-4" />
                            </button>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
