import type { LucideIcon } from "lucide-react";
import {
  // Combat / Weapon
  Anvil,
  Axe,
  Bomb,
  Construction,
  Cross,
  Crosshair,
  Crown,
  Gavel,
  Hammer,
  Pickaxe,
  PocketKnife,
  Skull,
  Slice,
  Sword,
  Swords,
  Target,
  Trophy,
  Wand,
  WandSparkles,
  // Defense / Protection
  BrickWall,
  Castle,
  Fence,
  HardHat,
  Lock,
  LockKeyhole,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  ShieldPlus,
  // Elemental / Nature
  Clover,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Cloudy,
  Earth,
  Flower,
  Flower2,
  Leaf,
  LeafyGreen,
  Mountain,
  Rainbow,
  Shrub,
  Sprout,
  Sunrise,
  Sunset,
  Tornado,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  Wind,
  // Fire / Heat
  CookingPot,
  FireExtinguisher,
  Flame,
  FlameKindling,
  Fuel,
  Heater,
  ThermometerSun,
  // Ice / Cold
  IceCreamCone,
  MountainSnow,
  Snowflake,
  SunSnow,
  ThermometerSnowflake,
  // Water / Ocean
  Dam,
  Droplet,
  Droplets,
  Fish,
  Sailboat,
  Shell,
  ShowerHead,
  Waves,
  // Lightning / Energy
  PlugZap,
  Zap,
  // Light / Holy
  Church,
  Flashlight,
  FlashlightOff,
  Haze,
  Lightbulb,
  Medal,
  Sparkle,
  Sparkles,
  Star,
  StarHalf,
  StarOff,
  Stars,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  // Dark / Arcane
  CircleDot,
  CircleDotDashed,
  Drama,
  Eclipse,
  EyeClosed,
  Ghost,
  Moon,
  MoonStar,
  Omega,
  Orbit,
  Origami,
  Radiation,
  VenetianMask,
  // Poison / Toxin
  Biohazard,
  Cannabis,
  FlaskConical,
  FlaskRound,
  Pipette,
  SprayCan,
  Syringe,
  TestTube,
  TestTubes,
  // Psychic / Mind
  Brain,
  BrainCircuit,
  BrainCog,
  Ear,
  Eye,
  EyeOff,
  Fingerprint,
  Radar,
  ScanEye,
  ScanFace,
  Speech,
  Telescope,
  // Life / Healing
  Bandage,
  HandCoins,
  HandHeart,
  HandHelping,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Pill,
  PillBottle,
  ScanHeart,
  Stethoscope,
  // Crystal / Mineral
  Cone,
  Cuboid,
  Diamond,
  DiamondMinus,
  DiamondPlus,
  Gem,
  Hexagon,
  Pentagon,
  Pyramid,
  // Sound / Sonic
  AudioLines,
  AudioWaveform,
  Bell,
  BellElectric,
  BellRing,
  Drum,
  Guitar,
  Megaphone,
  Music,
  Music2,
  Piano,
  Volume2,
  // Time / Gravity
  Clock,
  History,
  Hourglass,
  Infinity,
  Magnet,
  RotateCcw,
  RotateCw,
  Timer,
  TimerReset,
  Weight,
  // Beast / Animal
  Bird,
  Bone,
  Bug,
  Cat,
  Dog,
  Drumstick,
  Egg,
  Feather,
  PawPrint,
  Rabbit,
  Rat,
  Snail,
  Squirrel,
  Turtle,
  Worm,
  // Tech / Construct
  Bolt,
  Bot,
  BotMessageSquare,
  CircuitBoard,
  Cog,
  Cpu,
  Gamepad2,
  HardDrive,
  Joystick,
  Microchip,
  Plug,
  Rocket,
  Satellite,
  Wrench,
  // Magic / Spell
  Atom,
  BookOpen,
  Dna,
  Scroll,
  ScrollText,
  Shapes,
  Variable,
  Waypoints,
  // People / Roles
  BicepsFlexed,
  CircleUser,
  Contact,
  HandMetal,
  PersonStanding,
  User,
  UserRound,
  Users,
  // Movement / Navigation
  Compass,
  Footprints,
  Globe,
  Landmark,
  Map,
  MapPin,
  Navigation2,
  Route,
  Signpost,
  // Buffs / Debuffs
  Activity,
  ArrowBigDown,
  ArrowBigUp,
  ArrowDown,
  ArrowUp,
  CircleArrowDown,
  CircleArrowUp,
  Gauge,
  Layers,
  Repeat,
  ShieldOff,
  TrendingDown,
  TrendingUp,
  VolumeOff,
  // Status Indicators
  AlertTriangle,
  Badge,
  BadgeAlert,
  BadgeCheck,
  CircleAlert,
  CircleCheck,
  CircleX,
  // Items / Equipment
  Archive,
  Backpack,
  Box,
  Coins,
  Dumbbell,
  Gift,
  Glasses,
  Package,
  Shirt,
  // Exploration / Utility
  Aperture,
  Blend,
  Bookmark,
  Flag,
  Focus,
  Hand,
  Milestone,
  Proportions,
  ScanSearch,
  Shovel,
  Siren,
  Spade,
  Tag,
  Tags,
  Tent,
  Wheat,
  Workflow,
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";

export interface IconGroup {
  label: string;
  icons: Record<string, LucideIcon>;
}

export const ICON_GROUPS: IconGroup[] = [
  {
    label: "Combat / Weapon",
    icons: {
      Anvil,
      Axe,
      Bomb,
      Construction,
      Cross,
      Crosshair,
      Crown,
      Gavel,
      Hammer,
      Pickaxe,
      PocketKnife,
      Skull,
      Slice,
      Sword,
      Swords,
      Target,
      Trophy,
      Wand,
      WandSparkles,
    },
  },
  {
    label: "Defense / Protection",
    icons: {
      BrickWall,
      Castle,
      Fence,
      HardHat,
      Lock,
      LockKeyhole,
      Shield,
      ShieldAlert,
      ShieldCheck,
      ShieldHalf,
      ShieldPlus,
    },
  },
  {
    label: "Elemental / Nature",
    icons: {
      Clover,
      Cloud,
      CloudDrizzle,
      CloudFog,
      CloudHail,
      CloudLightning,
      CloudMoon,
      CloudMoonRain,
      CloudRain,
      CloudRainWind,
      CloudSnow,
      CloudSun,
      Cloudy,
      Earth,
      Flower,
      Flower2,
      Leaf,
      LeafyGreen,
      Mountain,
      Rainbow,
      Shrub,
      Sprout,
      Sunrise,
      Sunset,
      Tornado,
      TreeDeciduous,
      TreePalm,
      TreePine,
      Trees,
      Wind,
    },
  },
  {
    label: "Fire / Heat",
    icons: {
      CookingPot,
      FireExtinguisher,
      Flame,
      FlameKindling,
      Fuel,
      Heater,
      ThermometerSun,
    },
  },
  {
    label: "Ice / Cold",
    icons: {
      IceCreamCone,
      MountainSnow,
      Snowflake,
      SunSnow,
      ThermometerSnowflake,
    },
  },
  {
    label: "Water / Ocean",
    icons: {
      Dam,
      Droplet,
      Droplets,
      Fish,
      Sailboat,
      Shell,
      ShowerHead,
      Waves,
    },
  },
  {
    label: "Lightning / Energy",
    icons: {
      PlugZap,
      Zap,
    },
  },
  {
    label: "Light / Holy",
    icons: {
      Church,
      Flashlight,
      FlashlightOff,
      Haze,
      Lightbulb,
      Medal,
      Sparkle,
      Sparkles,
      Star,
      StarHalf,
      StarOff,
      Stars,
      Sun,
      SunDim,
      SunMedium,
      SunMoon,
    },
  },
  {
    label: "Dark / Arcane",
    icons: {
      CircleDot,
      CircleDotDashed,
      Drama,
      Eclipse,
      EyeClosed,
      Ghost,
      Moon,
      MoonStar,
      Omega,
      Orbit,
      Origami,
      Radiation,
      VenetianMask,
    },
  },
  {
    label: "Poison / Toxin",
    icons: {
      Biohazard,
      Cannabis,
      FlaskConical,
      FlaskRound,
      Pipette,
      SprayCan,
      Syringe,
      TestTube,
      TestTubes,
    },
  },
  {
    label: "Psychic / Mind",
    icons: {
      Brain,
      BrainCircuit,
      BrainCog,
      Ear,
      Eye,
      EyeOff,
      Fingerprint,
      Radar,
      ScanEye,
      ScanFace,
      Speech,
      Telescope,
    },
  },
  {
    label: "Life / Healing",
    icons: {
      Bandage,
      HandCoins,
      HandHeart,
      HandHelping,
      Heart,
      HeartCrack,
      HeartHandshake,
      HeartOff,
      HeartPulse,
      Pill,
      PillBottle,
      ScanHeart,
      Stethoscope,
    },
  },
  {
    label: "Crystal / Mineral",
    icons: {
      Cone,
      Cuboid,
      Diamond,
      DiamondMinus,
      DiamondPlus,
      Gem,
      Hexagon,
      Pentagon,
      Pyramid,
    },
  },
  {
    label: "Sound / Sonic",
    icons: {
      AudioLines,
      AudioWaveform,
      Bell,
      BellElectric,
      BellRing,
      Drum,
      Guitar,
      Megaphone,
      Music,
      Music2,
      Piano,
      Volume2,
    },
  },
  {
    label: "Time / Gravity",
    icons: {
      Clock,
      History,
      Hourglass,
      Infinity,
      Magnet,
      RotateCcw,
      RotateCw,
      Timer,
      TimerReset,
      Weight,
    },
  },
  {
    label: "Beast / Animal",
    icons: {
      Bird,
      Bone,
      Bug,
      Cat,
      Dog,
      Drumstick,
      Egg,
      Feather,
      PawPrint,
      Rabbit,
      Rat,
      Snail,
      Squirrel,
      Turtle,
      Worm,
    },
  },
  {
    label: "Tech / Construct",
    icons: {
      Bolt,
      Bot,
      BotMessageSquare,
      CircuitBoard,
      Cog,
      Cpu,
      Gamepad2,
      HardDrive,
      Joystick,
      Microchip,
      Plug,
      Rocket,
      Satellite,
      Wrench,
    },
  },
  {
    label: "Magic / Spell",
    icons: {
      Atom,
      BookOpen,
      Dna,
      Scroll,
      ScrollText,
      Shapes,
      Variable,
      Waypoints,
    },
  },
  {
    label: "People / Roles",
    icons: {
      BicepsFlexed,
      CircleUser,
      Contact,
      HandMetal,
      PersonStanding,
      User,
      UserRound,
      Users,
    },
  },
  {
    label: "Movement / Navigation",
    icons: {
      Compass,
      Footprints,
      Globe,
      Landmark,
      Map,
      MapPin,
      Navigation2,
      Route,
      Signpost,
    },
  },
  {
    label: "Buffs / Debuffs",
    icons: {
      Activity,
      ArrowBigDown,
      ArrowBigUp,
      ArrowDown,
      ArrowUp,
      CircleArrowDown,
      CircleArrowUp,
      Gauge,
      Layers,
      Repeat,
      ShieldOff,
      TrendingDown,
      TrendingUp,
      VolumeOff,
    },
  },
  {
    label: "Status Indicators",
    icons: {
      AlertTriangle,
      Badge,
      BadgeAlert,
      BadgeCheck,
      CircleAlert,
      CircleCheck,
      CircleX,
    },
  },
  {
    label: "Items / Equipment",
    icons: {
      Archive,
      Backpack,
      Box,
      Coins,
      Dumbbell,
      Gift,
      Glasses,
      Package,
      Shirt,
    },
  },
  {
    label: "Exploration / Utility",
    icons: {
      Aperture,
      Blend,
      Bookmark,
      Flag,
      Focus,
      Hand,
      Milestone,
      Proportions,
      ScanSearch,
      Shovel,
      Siren,
      Spade,
      Tag,
      Tags,
      Tent,
      Wheat,
      Workflow,
    },
  },
];

export const ICON_MAP: Record<string, LucideIcon> = ICON_GROUPS.reduce<
  Record<string, LucideIcon>
>((acc, group) => ({ ...acc, ...group.icons }), {});

export const DEFAULT_ICON_KEY = "CircleDot";

interface IconPickerProps {
  value?: string;
  onValueChange: (value: string) => void;
}

export function IconPicker({ value = DEFAULT_ICON_KEY, onValueChange }: IconPickerProps) {
  return (
    <Select onValueChange={onValueChange} value={value}>
      <SelectTrigger>
        <SelectValue placeholder="Select an icon" />
      </SelectTrigger>
      <SelectContent>
        {ICON_GROUPS.map((group) => (
          <SelectGroup key={group.label}>
            <SelectLabel>{group.label}</SelectLabel>
            {Object.entries(group.icons).map(([key, Icon]) => (
              <SelectItem key={key} value={key}>
                <div className="flex items-center gap-2">
                  <Icon className="h-4 w-4" />
                  <span>{key}</span>
                </div>
              </SelectItem>
            ))}
          </SelectGroup>
        ))}
      </SelectContent>
    </Select>
  );
}
